### ISSUE TITLE
weird behavior with drag and drop with multiple dragable series

### ISSUE THREAD

**Issue by keithmdragon** [highcharts/draggable-points#43]
i took the bubble demo and modified it to be a scatter chart with 2 dragable series. 

example: http://jsfiddle.net/kdragon/xdwuup4j/

select any of the points and slowly drag them towards a point in the other series, notice the other series point keeps getting selected during the drag with selection and tooltip flickering

Thanks
Keith

**Comment by sebastianbochan** [comment]
+1

**Comment by sebastianbochan** [comment]
+1

**Comment by TorsteinHonsi** [comment]
Fixed by 6243233c13d938fcea74304296a739ad920e68d6

**Comment by keithmdragon** [comment]
there is still an issue when u simply select the point (no drag). it jumps back and forth between a couple points

with my original fiddle, click (just click, no drag) the black diamond in the middle and notice the tooltip and selection jump back and forth between it and the blue dot below it. you can also see it on mouse up after the drag

Thanks
Keith
