### ISSUE TITLE
Multiple series: select the point (no drag) - tooltip jumps back and forth between points

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/draggable-points#44]
This is continuation of #43 

**Example:** http://jsfiddle.net/kdragon/xdwuup4j/

**Steps:**
1. click (no drag) the black diamond in the middle 
2. tooltip and selection jump back and forth between series (the blue dot below clicked point)

You can also see it on mouse up after the drag.

**Comment by keithmdragon** [comment]
i'm really hoping this can be fixed soon. we have code in production that has been effected weeks by this

Thanks
Keith

**Comment by TorsteinHonsi** [comment]
Sorry for the delay, Easter and all... It is fixed now, as seen in http://jsfiddle.net/kdragon/xdwuup4j/.

**Comment by keithmdragon** [comment]
Hi Torstein,

after applying the change or running the fiddle:  http://jsfiddle.net/kdragon/xdwuup4j/. i'm still seeing the same issue.

same instructions:

1. click (no drag) the black diamond in the middle 
2. tooltip and selection jump back and forth between series (the blue dot below clicked point)

i see this behavior for any point i click, black or blue

Thanks
Keith

**Comment by TorsteinHonsi** [comment]
Oh, sorry about that, I was sure I had it working, but I can also see this now. I'll check it out.

**Comment by TorsteinHonsi** [comment]
Now it works as far as I can see: http://jsfiddle.net/highcharts/xdwuup4j/1/

**Comment by KacperMadej** [comment]
Problem is still visible on Win7/Chrome - after click, tooltip jumps to another series.

**Comment by keithmdragon** [comment]
i confirm that this is still an issue

**Comment by TorsteinHonsi** [comment]
Ok, this turned out to be a touch one. Please try now: http://jsfiddle.net/highcharts/xdwuup4j/2/

**Comment by KacperMadej** [comment]
The problem is resolved on Win7/Chrome :+1:
